// Pure easing preset functions. Each maps normalized progress u in [0,1] to an eased value.
// f(0) === 0 and f(1) === 1 EXACTLY for all eight (DECISIONS.md #14) — endpoints are special-cased
// rather than trusted to fall out of the floating-point formula, per the fixture's committed
// invariant. Back and Bounce may leave [0,1] in the interior (overshoot / settle bounce) — that is
// the point of them.
//
// Values here are generated by the identical math used to build
// src/timeline/fixtures/easing_expected.json (see that file's provenance note) — the fixture is
// the committed ground truth; this file is written to match it, not the other way around.

import type { EasingPreset } from "./types";

export type EasingFn = (u: number) => number;

function cubicEaseIn(u: number): number {
  return u * u * u;
}

function cubicEaseOut(u: number): number {
  const inv = 1 - u;
  return 1 - inv * inv * inv;
}

function cubicEaseInOut(u: number): number {
  if (u < 0.5) return 4 * u * u * u;
  const inv = -2 * u + 2;
  return 1 - (inv * inv * inv) / 2;
}

function sineInOut(u: number): number {
  return (1 - Math.cos(Math.PI * u)) / 2;
}

// easeOutBack — standard overshoot constants (c1 = 1.70158, c3 = c1 + 1).
function back(u: number): number {
  const c1 = 1.70158;
  const c3 = c1 + 1;
  const s = u - 1;
  return 1 + c3 * s * s * s + c1 * s * s;
}

// easeOutBounce — piecewise, per blender-fcurve-craft's note that Bounce needs a piecewise
// function rather than a single cubic-bezier (reviews/codex_review_S4.md risk #3).
function bounce(u: number): number {
  const n1 = 7.5625;
  const d1 = 2.75;
  let t = u;
  if (t < 1 / d1) {
    return n1 * t * t;
  } else if (t < 2 / d1) {
    t -= 1.5 / d1;
    return n1 * t * t + 0.75;
  } else if (t < 2.5 / d1) {
    t -= 2.25 / d1;
    return n1 * t * t + 0.9375;
  } else {
    t -= 2.625 / d1;
    return n1 * t * t + 0.984375;
  }
}

// Constant — holds the left key's value for every u < 1 (SPEC target #1); only reaches the right
// key's value (1) exactly at u === 1, i.e. at the next key's own time.
function constant(u: number): number {
  return u >= 1 ? 1 : 0;
}

function wrapExactEndpoints(fn: EasingFn): EasingFn {
  return (u: number) => {
    if (u <= 0) return 0;
    if (u >= 1) return 1;
    return fn(u);
  };
}

export const EASING: Record<EasingPreset, EasingFn> = {
  linear: wrapExactEndpoints((u) => u),
  easeIn: wrapExactEndpoints(cubicEaseIn),
  easeOut: wrapExactEndpoints(cubicEaseOut),
  easeInOut: wrapExactEndpoints(cubicEaseInOut),
  sineInOut: wrapExactEndpoints(sineInOut),
  back: wrapExactEndpoints(back),
  bounce: wrapExactEndpoints(bounce),
  constant: wrapExactEndpoints(constant),
};

export function ease(preset: EasingPreset, u: number): number {
  const fn = EASING[preset];
  return fn(u);
}
